port: 1234
endpoints:
    - request:
        path: /api/v1/todos
        method: GET
      response:
        code: 200
        body: todos.json
        headers:
            content-type: text/json

    - request:
        path: /api/v1/user
        method: GET
      response:
        code: 200
        body: user.json
        headers:
            content-type: text/json
